version: "3.7"

services:
    express-app:
        image: "${EXPRESS_APP_IMAGE}" # set this when deploying
        ports:
            - "3000:3000"

    nginx:
        image: nginx:1.25.1
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "express-app"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - certbot-etc:/etc/letsencrypt # ssl shit
            - certbot-var:/var/lib/letsencrypt # ssl shit
            - web-root:/var/www/html #nginx html index folder
            - dhparam:/etc/ssl/certs # ssl shit
            - web-default-root:/var/www/default #nginx html error default folder

    # Generates SSL certificates
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - "nginx"
        command: certonly --webroot --webroot-path=/var/www/html --email viictor.ivan@gmail.com --agree-tos --no-eff-email --force-renewal -d apps.kddw.com.br

volumes:
    certbot-etc:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./certbot/etc
    certbot-var:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./certbot/var
    web-root:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./nginx/www/html
    dhparam:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./nginx/dhparam/
    web-default-root:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./nginx/www/default
